name: nyaya_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ✅ Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.3
  firebase_analytics: ^12.0.2
  url_launcher: ^6.3.2
  # ✅ UI and Utilities
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  file_picker: ^10.3.3
  lottie: ^3.3.2
  rive: ^0.13.20
  table_calendar: ^3.2.0
  open_filex: ^4.7.0
  http: ^1.5.0
  pinput: ^5.0.1
  image_picker: ^1.2.0
  share_plus: ^12.0.0
  intl: ^0.20.0
  # ✅ Auth integrations
  google_sign_in: ^6.3.0

  # ✅ Environment & API keys
  flutter_dotenv: ^6.0.0

  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/onboarding1.jpg
    - assets/onboarding2.jpg
    - assets/onboarding3.jpg
    - assets/google.jpg
    - assets/microsoft.jpg
    - assets/facebook.png
    - assets/linkedin.png
    - assets/verification.json
    #- assets/blank_profile.png
    #- assets/learning_placeholder.png
    #- assets/profile_icon.riv
    - .env
